---
- name: Install Grafana and Prometheus
  hosts: Npontu2
  become: true  # Run tasks as a privileged user (e.g., root)

  tasks:
    - name: Update apt package cache (for Ubuntu systems)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install dependencies
      package:
        name:
          - software-properties-common  # for adding repositories
          - apt-transport-https  # for accessing packages over HTTPS
      become: true
      when: ansible_os_family == 'Debian'

    - name: Add Grafana APT repository (for Ubuntu)
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Prometheus APT repository (for Ubuntu)
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Grafana and Prometheus
      apt:
        name:
          - grafana
          - prometheus
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
